export const routeDescriptions: Record<string, string> = {
  '/dashboard': 'An executive overview of service performance, workflow health, and financial highlights.',
  '/analytics': 'Monitor live operational performance, capacity utilization, and optimization insights.',
  '/analytics/optimized': 'Deep dive into branch analytics with real-time telemetry and capacity intelligence.',
  '/deliveryman': 'Monitor delivery driver availability, performance metrics, and active assignments.',
  '/branches': 'Inspect branch throughput, capacity, and SLA adherence across the network.',
  '/hub/payments': 'Track hub-level payouts, pending reconciliations, and settlement status.',
  '/merchants': 'Manage merchant accounts, contractual terms, and escalation notes.',
  '/merchant/payments': 'Review merchant remittances, COD balances, and financial exceptions.',
  '/todo': 'Prioritise operational tasks and approvals that need immediate attention.',
  '/support': 'Supervise support queues, escalation pipelines, and SLAs for customer communication.',
  '/support/create': 'Create a new support ticket to address customer inquiries and issues.',
  '/support/:id': 'Review an individual support ticket, including requester context and chat history.',
  '/support/:id/edit': 'Update support ticket details, assignments, or priority to keep work moving.',
  '/parcels': 'Dive into parcel statuses, exception workflows, and delivery pipelines.',
  '/bookings': 'Oversee booking requests, SLA timers, and channel split.',
  '/shipments': 'Track shipments from creation to delivery with milestone visibility.',
  '/branches/clients': 'Monitor local client activity, retention, and service levels per branch.',
  '/branches/shipments': 'Review branch-specific shipment pipelines and workflow bottlenecks.',
  '/branches/hierarchy': 'Visualise branch hierarchy, reporting lines, and coverage zones.',
  '/tracking': 'Live-map parcel movement, rider positions, and delivery progress.',
  '/workflow': 'Manage workflow orchestration across operations teams with full visibility.',
  '/bags': 'Coordinate bag assembly, dispatch, and reconciliation workflows.',
  '/linehaul': 'Plan and review linehaul transport legs and carrier utilisation.',
  '/manifests': 'Generate and audit manifests before handoff to partners and carriers.',
  '/ecmr': 'Access digital consignment notes for compliance and liability tracking.',
  '/scans': 'Audit scan events and investigate missed checkpoints.',
  '/routes': 'Configure delivery routes, stops, and driver assignments.',
  '/customers': 'Explore the customer directory and account health signals.',
  '/customers/create': 'Onboard a new customer with verified profiles and onboarding tasks.',
  '/quotations': 'Prepare and track sales quotations for high-value accounts.',
  '/contracts': 'Manage contractual terms, renewals, and compliance checkpoints.',
  '/address-book': 'Maintain shipping address books and preferred fulfilment details.',
  '/rate-cards': 'Configure pricing matrices and zone-based rate cards.',
  '/invoices': 'Review invoice lifecycles, payment status, and adjustments.',
  '/settlements': 'Balance settlements across merchants, hubs, and riders.',
  '/payroll/generate': 'Generate payroll runs with transparent breakdowns.',
  '/payroll': 'Audit payroll history, payments, and flags.',
  '/search': 'Run cross-module searches with advanced filters.',
  '/reports/parcels': 'Construct parcel performance and SLA analytic reports.',
  '/reports/salary': 'Analyse salary cost trends and payroll liabilities.',
  '/logs': 'Inspect recent system activities and operations audit events.',
  '/settings/roles': 'Administer system roles and permission boundaries.',
  '/settings/users': 'Manage user access, invitations, and account security.',
  '/settings/departments': 'Organise departments, reporting lines, and escalation paths.',
  '/settings/general': 'Calibrate core platform settings and company branding.',
  '/settings/delivery-charge': 'Configure delivery charge rules and zone coverage.',
  '/settings/sms': 'Manage SMS gateways and message templates.',
  '/settings/notifications': 'Fine-tune notification channels and delivery preferences.',
};
