<?php

return [
    // Collapsible buckets in the admin sidebar
    'buckets' => [
        'menu' => [
            'label_trans_key' => 'menus.menu',
            'children' => [
                [
                    'key' => 'dashboard',
                    'label_trans_key' => 'menus.dashboard',
                    'icon' => 'fa fa-home',
                    'route' => 'admin.dashboard',
                    'active_patterns' => ['admin.dashboard'],
                    'permission_check' => null,
                    'expanded' => true,
                    'children' => [
                        [
                            'key' => 'dashboard_overview',
                            'label_trans_key' => 'menus.overview',
                            'icon' => 'fa fa-tachometer-alt',
                            'route' => 'admin.dashboard',
                            'active_patterns' => ['admin.dashboard'],
                            'permission_check' => null,
                        ],
                        [
                            'key' => 'dashboard_analytics',
                            'label_trans_key' => 'menus.analytics',
                            'icon' => 'fa fa-chart-line',
                            'route' => 'admin.dashboard.analytics',
                            'active_patterns' => ['admin.dashboard.analytics'],
                            'permission_check' => null,
                        ],
                        [
                            'key' => 'dashboard_reports',
                            'label_trans_key' => 'menus.reports',
                            'icon' => 'fa fa-file-text',
                            'route' => 'admin.dashboard.reports',
                            'active_patterns' => ['admin.dashboard.reports'],
                            'permission_check' => null,
                        ],
                    ],
                ],
                [
                    'key' => 'deliveryman',
                    'label_trans_key' => 'menus.delivery_drivers',
                    'icon' => 'fa fa-users',
                    'route' => 'admin.deliveryman.index',
                    'active_patterns' => ['admin.deliveryman.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\DeliveryMan',
                ],
                [
                    'key' => 'branch_manage',
                    'label_trans_key' => 'menus.branch_management',
                    'icon' => 'fa fa-building',
                    'active_patterns' => ['admin.hubs.*', 'admin.hub.payments.*'],
                    'children' => [
                        [
                            'key' => 'branches',
                            'label_trans_key' => 'menus.branches',
                            'icon' => 'fa fa-building',
                            'route' => 'admin.hubs.index',
                            'active_patterns' => ['admin.hubs.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Hub',
                        ],
                        [
                            'key' => 'hub_payments',
                            'label_trans_key' => 'menus.payments',
                            'icon' => 'fa fa-credit-card',
                            'route' => 'admin.hub.payments',
                            'active_patterns' => ['admin.hub.payments.*'],
                            'permission_check' => 'hasPermission:hub_payments_read',
                        ],
                    ],
                ],
                [
                    'key' => 'merchant_manage',
                    'label_trans_key' => 'menus.merchant_management',
                    'icon' => 'fa fa-store',
                    'active_patterns' => ['admin.merchants.*', 'admin.merchant.payments.*'],
                    'children' => [
                        [
                            'key' => 'merchants',
                            'label_trans_key' => 'menus.merchants',
                            'icon' => 'fa fa-user',
                            'route' => 'admin.merchants.index',
                            'active_patterns' => ['admin.merchants.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Merchant',
                        ],
                        [
                            'key' => 'merchant_payments',
                            'label_trans_key' => 'menus.payments',
                            'icon' => 'fa fa-dollar-sign',
                            'route' => 'admin.merchant.payments',
                            'active_patterns' => ['admin.merchant.payments.*'],
                            'permission_check' => 'hasPermission:merchant_payments_read',
                        ],
                    ],
                ],
                [
                    'key' => 'sales',
                    'label_trans_key' => 'menus.sales',
                    'icon' => 'fa fa-handshake',
                    'expanded' => true,
                    'active_patterns' => [
                        'admin.customers.*',
                        'admin.quotations.*',
                        'admin.contracts.*',
                        'admin.address-book.*',
                    ],
                    'children' => [
                        [
                            'key' => 'sales_customers',
                            'label_trans_key' => 'menus.customers',
                            'icon' => 'fa fa-users',
                            'expanded' => true,
                            'active_patterns' => ['admin.customers.*'],
                            'children' => [
                                [
                                    'key' => 'sales_customers_all',
                                    'label_trans_key' => 'menus.customers_all',
                                    'icon' => 'fa fa-address-book',
                                    'route' => 'admin.customers.index',
                                    'active_patterns' => [
                                        'admin.customers.index',
                                        'admin.customers.show',
                                        'admin.customers.edit',
                                    ],
                                    'permission_check' => 'can:viewAny,App\\Models\\Customer',
                                ],
                                [
                                    'key' => 'sales_customers_create',
                                    'label_trans_key' => 'menus.customers_create',
                                    'icon' => 'fa fa-user-plus',
                                    'route' => 'admin.customers.create',
                                    'active_patterns' => ['admin.customers.create'],
                                    'permission_check' => 'can:create,App\\Models\\Customer',
                                ],
                            ],
                        ],
                        [
                            'key' => 'sales_quotations',
                            'label_trans_key' => 'menus.quotations',
                            'icon' => 'fa fa-file-signature',
                            'route' => 'admin.quotations.index',
                            'active_patterns' => ['admin.quotations.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Quotation',
                        ],
                        [
                            'key' => 'sales_contracts',
                            'label_trans_key' => 'menus.contracts',
                            'icon' => 'fa fa-file-contract',
                            'route' => 'admin.contracts.index',
                            'active_patterns' => ['admin.contracts.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Contract',
                        ],
                        [
                            'key' => 'sales_address_book',
                            'label_trans_key' => 'menus.address_book',
                            'icon' => 'fa fa-address-card',
                            'route' => 'admin.address-book.index',
                            'active_patterns' => ['admin.address-book.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\AddressBook',
                        ],
                    ],
                ],
                [
                    'key' => 'todo',
                    'label_trans_key' => 'menus.todo_list',
                    'icon' => 'fa fa-check-square',
                    'route' => 'admin.todo',
                    'active_patterns' => ['admin.todo'],
                    'permission_check' => null,
                ],
                [
                    'key' => 'support',
                    'label_trans_key' => 'menus.support',
                    'icon' => 'fa fa-message-square',
                    'route' => 'admin.support',
                    'active_patterns' => ['admin.support'],
                    'permission_check' => null,
                ],
                [
                    'key' => 'parcel',
                    'label_trans_key' => 'menus.parcels',
                    'icon' => 'fa fa-box',
                    'route' => 'admin.parcels.index',
                    'active_patterns' => ['admin.parcels.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\Parcel',
                ],
            ],
        ],

        'operations' => [
            'label_trans_key' => 'menus.operations',
            'children' => [
                // Booking wizard (create shipment)
                [
                    'key' => 'bookings',
                    'label_trans_key' => 'menus.bookings',
                    'icon' => 'fa fa-clipboard-plus',
                    'route' => 'admin.booking.step1',
                    'active_patterns' => ['admin.booking.*'],
                    'permission_check' => 'can:create,App\\Models\\Shipment',
                ],
                // Core ops
                [
                    'key' => 'shipments',
                    'label_trans_key' => 'menus.shipments',
                    'icon' => 'fa fa-box',
                    'route' => 'admin.shipments.index',
                    'active_patterns' => ['admin.shipments.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\Shipment',
                ],
                [
                    'key' => 'bags',
                    'label_trans_key' => 'menus.bags',
                    'icon' => 'fa fa-layer-group',
                    'route' => 'admin.bags.index',
                    'active_patterns' => ['admin.bags.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\Bag',
                ],
                // Linehaul group
                [
                    'key' => 'linehaul_group',
                    'label_trans_key' => 'menus.linehaul',
                    'icon' => 'fa fa-route',
                    'children' => [
                        [
                            'key' => 'linehaul_legs',
                            'label_trans_key' => 'menus.linehaul',
                            'icon' => 'fa fa-route',
                            'route' => 'admin.linehaul-legs.index',
                            'active_patterns' => ['admin.linehaul-legs.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\TransportLeg',
                        ],
                        [
                            'key' => 'awb_stock',
                            'label_trans_key' => 'menus.awb_stock',
                            'icon' => 'fa fa-ticket-alt',
                            'route' => 'admin.awb-stock.index',
                            'active_patterns' => ['admin.awb-stock.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\AwbStock',
                        ],
                        [
                            'key' => 'manifests',
                            'label_trans_key' => 'menus.manifests',
                            'icon' => 'fa fa-list',
                            'route' => 'admin.manifests.index',
                            'active_patterns' => ['admin.manifests.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Manifest',
                        ],
                        [
                            'key' => 'ecmr',
                            'label_trans_key' => 'menus.e_cmr',
                            'icon' => 'fa fa-road',
                            'route' => 'admin.ecmr.index',
                            'active_patterns' => ['admin.ecmr.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Ecmr',
                        ],
                    ],
                ],
                [
                    'key' => 'scan_events',
                    'label_trans_key' => 'menus.scan_events',
                    'icon' => 'fa fa-barcode',
                    'route' => 'admin.scans.index',
                    'active_patterns' => ['admin.scans.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\ScanEvent',
                ],
                [
                    'key' => 'routes',
                    'label_trans_key' => 'menus.routes_stops',
                    'icon' => 'fa fa-truck',
                    'route' => 'admin.routes.index',
                    'active_patterns' => ['admin.routes.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\Route',
                ],
                [
                    'key' => 'epod',
                    'label_trans_key' => 'menus.epod_gallery',
                    'icon' => 'fa fa-file-signature',
                    'route' => 'admin.epod.index',
                    'active_patterns' => ['admin.epod.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\Epod',
                ],
                [
                    'key' => 'control_board',
                    'label_trans_key' => 'menus.dashboard',
                    'icon' => 'fa fa-tachometer-alt',
                    'route' => 'admin.control.board',
                    'active_patterns' => ['admin.control.board'],
                    'permission_check' => 'hasPermission:control_board_read',
                ],
                // Network configuration
                [
                    'key' => 'zones_lanes',
                    'label_trans_key' => 'menus.zones_lanes',
                    'icon' => 'fa fa-project-diagram',
                    'active_patterns' => ['admin.zones.*', 'admin.lanes.*'],
                    'children' => [
                        [
                            'key' => 'zones',
                            'label_trans_key' => 'menus.zones_lanes',
                            'icon' => 'fa fa-project-diagram',
                            'route' => 'admin.zones.index',
                            'active_patterns' => ['admin.zones.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Zone',
                        ],
                        [
                            'key' => 'lanes',
                            'label_trans_key' => 'menus.zones_lanes',
                            'icon' => 'fa fa-project-diagram',
                            'route' => 'admin.lanes.index',
                            'active_patterns' => ['admin.lanes.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Lane',
                        ],
                    ],
                ],
                [
                    'key' => 'carriers_services',
                    'label_trans_key' => 'menus.carriers_services',
                    'icon' => 'fa fa-plane',
                    'active_patterns' => ['admin.carriers.*', 'admin.carrier-services.*'],
                    'children' => [
                        [
                            'key' => 'carriers',
                            'label_trans_key' => 'menus.carriers_services',
                            'icon' => 'fa fa-plane',
                            'route' => 'admin.carriers.index',
                            'active_patterns' => ['admin.carriers.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\Carrier',
                        ],
                        [
                            'key' => 'carrier_services',
                            'label_trans_key' => 'menus.carriers_services',
                            'icon' => 'fa fa-plane',
                            'route' => 'admin.carrier-services.index',
                            'active_patterns' => ['admin.carrier-services.*'],
                            'permission_check' => 'can:viewAny,App\\Models\\CarrierService',
                        ],
                    ],
                ],
                [
                    'key' => 'dispatch',
                    'label_trans_key' => 'menus.pickup_dispatch',
                    'icon' => 'fa fa-shipping-fast',
                    'route' => 'admin.dispatch.index',
                    'active_patterns' => ['admin.dispatch.index'],
                    'permission_check' => null,
                ],
                [
                    'key' => 'pickup_request',
                    'label_trans_key' => 'menus.pickup_request',
                    'icon' => 'fa fa-truck-moving',
                    'active_patterns' => ['pickup.request.*'],
                    'children' => [
                        [
                            'key' => 'pickup_regular',
                            'label_trans_key' => 'menus.regular',
                            'icon' => 'fa fa-truck',
                            'route' => 'pickup.request.regular',
                            'active_patterns' => ['pickup.request.regular'],
                            'permission_check' => 'hasPermission:pickup_request_regular',
                        ],
                        [
                            'key' => 'pickup_express',
                            'label_trans_key' => 'menus.express',
                            'icon' => 'fa fa-bolt',
                            'route' => 'pickup.request.express',
                            'active_patterns' => ['pickup.request.express'],
                            'permission_check' => 'hasPermission:pickup_request_express',
                        ],
                    ],
                ],
                // Asset management cluster (ops tooling)
                [
                    'key' => 'asset_management',
                    'label_trans_key' => 'menus.asset_management',
                    'icon' => 'fa fa-sitemap',
                    'active_patterns' => ['asset-category.*', 'asset.*', 'fuels.*', 'maintenance.*', 'accident.*'],
                    'children' => [
                        [
                            'key' => 'asset_categories',
                            'label_trans_key' => 'menus.assets_category',
                            'icon' => 'fa fa-folder',
                            'route' => 'asset-category.index',
                            'active_patterns' => ['asset-category.*'],
                            'permission_check' => 'hasPermission:asset_category_read',
                        ],
                        [
                            'key' => 'assets',
                            'label_trans_key' => 'menus.assets',
                            'icon' => 'fa fa-boxes',
                            'route' => 'asset.index',
                            'active_patterns' => ['asset.*'],
                            'permission_check' => 'hasPermission:assets_read',
                        ],
                        [
                            'key' => 'fuels',
                            'label_trans_key' => 'levels.fuels',
                            'icon' => 'fa fa-gas-pump',
                            'route' => 'fuels.index',
                            'active_patterns' => ['fuels.*'],
                            'permission_check' => 'hasPermission:fuels_read',
                        ],
                        [
                            'key' => 'maintenances',
                            'label_trans_key' => 'levels.maintenances',
                            'icon' => 'fa fa-tools',
                            'route' => 'maintenance.index',
                            'active_patterns' => ['maintenance.*'],
                            'permission_check' => 'hasPermission:maintenance_read',
                        ],
                        [
                            'key' => 'accidents',
                            'label_trans_key' => 'levels.accidents',
                            'icon' => 'fa fa-car-crash',
                            'route' => 'accident.index',
                            'active_patterns' => ['accident.*'],
                            'permission_check' => 'hasPermission:accidents_read',
                        ],
                        [
                            'key' => 'asset_reports',
                            'label_trans_key' => 'levels.reports',
                            'icon' => 'fa fa-chart-bar',
                            'route' => 'assets.reports',
                            'active_patterns' => ['assets.reports'],
                            'permission_check' => 'hasPermission:assets_reports',
                        ],
                    ],
                ],
            ],
        ],

        'sales' => [
            'label_trans_key' => 'menus.sales',
            'children' => [
                // Customers grouping (keep all existing feature links)
                [
                    'key' => 'customers',
                    'label_trans_key' => 'menus.customers',
                    'icon' => 'fa fa-users',
                    'active_patterns' => ['admin.customers.*'],
                    'children' => [
                        [
                            'key' => 'customers_index',
                            'label_trans_key' => 'menus.customers_all',
                            'icon' => 'fa fa-users',
                            'route' => 'admin.customers.index',
                            'active_patterns' => ['admin.customers.index'],
                            'permission_check' => 'can:viewAny,App\\Models\\Customer',
                        ],
                        [
                            'key' => 'customers_create',
                            'label_trans_key' => 'menus.customers_create',
                            'icon' => 'fa fa-user-plus',
                            'route' => 'admin.customers.create',
                            'active_patterns' => ['admin.customers.create'],
                            'permission_check' => 'can:create,App\\Models\\Customer',
                        ],
                    ],
                ],
                [
                    'key' => 'quotations',
                    'label_trans_key' => 'menus.quotations',
                    'icon' => 'fa fa-file-signature',
                    'route' => 'admin.quotations.index',
                    'active_patterns' => ['admin.quotations.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\Quotation',
                ],
                [
                    'key' => 'contracts',
                    'label_trans_key' => 'menus.contracts',
                    'icon' => 'fa fa-handshake',
                    'route' => 'admin.contracts.index',
                    'active_patterns' => ['admin.contracts.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\Contract',
                ],
                [
                    'key' => 'address_book',
                    'label_trans_key' => 'menus.address_book',
                    'icon' => 'fa fa-address-book',
                    'route' => 'admin.address-book.index',
                    'active_patterns' => ['admin.address-book.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\AddressBook',
                ],
            ],
        ],

        'compliance' => [
            'label_trans_key' => 'menus.compliance',
            'children' => [
                [
                    'key' => 'kyc',
                    'label_trans_key' => 'menus.kyc_screening',
                    'icon' => 'fa fa-id-card',
                    'route' => 'admin.kyc.index',
                    'active_patterns' => ['admin.kyc.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\KycRecord',
                ],
                [
                    'key' => 'dg',
                    'label_trans_key' => 'menus.dg_console',
                    'icon' => 'fa fa-exclamation-triangle',
                    'route' => 'admin.dg.index',
                    'active_patterns' => ['admin.dg.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\DangerousGood',
                ],
                [
                    'key' => 'ics2',
                    'label_trans_key' => 'menus.ics2_monitor',
                    'icon' => 'fa fa-shield-alt',
                    'route' => 'admin.ics2.index',
                    'active_patterns' => ['admin.ics2.*'],
                    'permission_check' => 'hasPermission:ics2_read',
                ],
                [
                    'key' => 'commodities',
                    'label_trans_key' => 'menus.commodities_hs_codes',
                    'icon' => 'fa fa-list',
                    'route' => 'admin.commodities.index',
                    'active_patterns' => ['admin.commodities.*', 'admin.hs-codes.*'],
                    'permission_check' => 'hasPermission:commodities_read|hasPermission:hscodes_read',
                ],
                [
                    'key' => 'customs_docs',
                    'label_trans_key' => 'menus.customs_docs',
                    'icon' => 'fa fa-file-invoice',
                    'route' => 'admin.customs-docs.index',
                    'active_patterns' => ['admin.customs-docs.*'],
                    'permission_check' => 'hasPermission:customs_docs_read',
                ],
                [
                    'key' => 'dps',
                    'label_trans_key' => 'menus.dps',
                    'icon' => 'fa fa-user-slash',
                    'route' => 'admin.dps.index',
                    'active_patterns' => ['admin.dps.*'],
                    'permission_check' => 'hasPermission:dps_read',
                ],
            ],
        ],

        'finance' => [
            'label_trans_key' => 'menus.finance',
            'children' => [
                [
                    'key' => 'rate_cards',
                    'label_trans_key' => 'menus.rate_cards',
                    'icon' => 'fa fa-calculator',
                    'route' => 'admin.rate-cards.index',
                    'active_patterns' => ['admin.rate-cards.*'],
                    'permission_check' => 'hasPermission:ratecards_read',
                ],
                [
                    'key' => 'invoices',
                    'label_trans_key' => 'menus.invoices',
                    'icon' => 'fa fa-file-invoice-dollar',
                    'route' => 'admin.invoices.index',
                    'active_patterns' => ['admin.invoices.*'],
                    'permission_check' => 'hasPermission:invoices_read',
                ],
                [
                    'key' => 'cod_receipts',
                    'label_trans_key' => 'menus.cod_receipts',
                    'icon' => 'fa fa-hand-holding-usd',
                    'route' => 'admin.cod-receipts.index',
                    'active_patterns' => ['admin.cod-receipts.*'],
                    'permission_check' => 'hasPermission:cod_receipts_read',
                ],
                [
                    'key' => 'settlements',
                    'label_trans_key' => 'menus.settlements',
                    'icon' => 'fa fa-exchange-alt',
                    'route' => 'admin.settlements.index',
                    'active_patterns' => ['admin.settlements.*'],
                    'permission_check' => 'hasPermission:settlements_read',
                ],
                [
                    'key' => 'cash_office',
                    'label_trans_key' => 'menus.cash_office',
                    'icon' => 'fa fa-cash-register',
                    'route' => 'admin.cash-office.index',
                    'active_patterns' => ['admin.cash-office.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\CashOffice',
                ],
                [
                    'key' => 'surcharges',
                    'label_trans_key' => 'menus.surcharge_rules',
                    'icon' => 'fa fa-calculator',
                    'route' => 'admin.surcharges.index',
                    'active_patterns' => ['admin.surcharges.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\SurchargeRule',
                ],
                [
                    'key' => 'fx_rates',
                    'label_trans_key' => 'menus.fx_rates',
                    'icon' => 'fa fa-dollar-sign',
                    'route' => 'admin.fx.index',
                    'active_patterns' => ['admin.fx.*'],
                    'permission_check' => 'can:viewAny,App\\Models\\FxRate',
                ],
                [
                    'key' => 'gl_export',
                    'label_trans_key' => 'menus.gl_export',
                    'icon' => 'fa fa-file-csv',
                    'route' => 'admin.gl-export.index',
                    'active_patterns' => ['admin.gl-export.*'],
                    'permission_check' => null,
                ],

                [
                    'key' => 'payroll',
                    'label_trans_key' => 'salary.payroll',
                    'icon' => 'fas fa-hand-holding-usd',
                    'active_patterns' => ['salary.generate.*', 'salary.*'],
                    'children' => [
                        [
                            'key' => 'salary_generate',
                            'label_trans_key' => 'salary.salary_generate',
                            'icon' => 'fa fa-calculator',
                            'route' => 'salary.generate.index',
                            'active_patterns' => ['salary.generate.*'],
                            'permission_check' => 'hasPermission:salary_generate_read',
                        ],
                        [
                            'key' => 'salary_index',
                            'label_trans_key' => 'menus.salary',
                            'icon' => 'fa fa-money-bill',
                            'route' => 'salary.index',
                            'active_patterns' => ['salary.*'],
                            'permission_check' => 'hasPermission:salary_read',
                        ],
                    ],
                ],

                // Legacy Finance: Accounts cluster
                [
                    'key' => 'accounts',
                    'label_trans_key' => 'menus.accounts',
                    'icon' => 'fas fa-user',
                    'active_patterns' => ['accounts.*', 'fund-transfer.*', 'account.heads.*', 'bank-transaction.*', 'cash.received.deliveryman.*', 'hub-panel.payment-request.*', 'paid.invoice.*'],
                    'children' => [
                        [
                            'key' => 'account_heads',
                            'label_trans_key' => 'menus.account_heads',
                            'icon' => 'fa fa-list',
                            'route' => 'account.heads.index',
                            'active_patterns' => ['account.heads.*'],
                            'permission_check' => 'hasPermission:account_heads_read',
                        ],
                        [
                            'key' => 'accounts_index',
                            'label_trans_key' => 'menus.accounts',
                            'icon' => 'fa fa-user',
                            'route' => 'accounts.index',
                            'active_patterns' => ['accounts.*'],
                            'permission_check' => 'hasPermission:account_read',
                        ],
                        [
                            'key' => 'fund_transfer',
                            'label_trans_key' => 'menus.fund_transfer',
                            'icon' => 'fa fa-exchange-alt',
                            'route' => 'fund-transfer.index',
                            'active_patterns' => ['fund-transfer.*'],
                            'permission_check' => 'hasPermission:fund_transfer_read',
                        ],
                        [
                            'key' => 'income',
                            'label_trans_key' => 'menus.income',
                            'icon' => 'fa fa-arrow-down',
                            'route' => 'income.index',
                            'active_patterns' => ['income.*'],
                            'permission_check' => 'hasPermission:income_read',
                        ],
                        [
                            'key' => 'expense',
                            'label_trans_key' => 'menus.expense',
                            'icon' => 'fa fa-arrow-up',
                            'route' => 'expense.index',
                            'active_patterns' => ['expense.*'],
                            'permission_check' => 'hasPermission:expense_read',
                        ],
                        [
                            'key' => 'bank_transaction',
                            'label_trans_key' => 'menus.bank_transaction',
                            'icon' => 'fa fa-university',
                            'route' => 'bank-transaction.index',
                            'active_patterns' => ['bank-transaction.*'],
                            'permission_check' => 'hasPermission:bank_transaction_read',
                        ],
                        [
                            'key' => 'cash_received',
                            'label_trans_key' => 'permissions.cash_received_from_delivery_man',
                            'icon' => 'fa fa-hand-holding-usd',
                            'route' => 'cash.received.deliveryman.index',
                            'active_patterns' => ['cash.received.deliveryman.*'],
                            'permission_check' => 'hasPermission:cash_received_from_delivery_man_read',
                        ],
                        [
                            'key' => 'hub_payment_request',
                            'label_trans_key' => 'menus.hub_payment_request',
                            'icon' => 'fa fa-handshake',
                            'route' => 'hub-panel.payment-request.index',
                            'active_patterns' => ['hub-panel.payment-request.*'],
                            'permission_check' => 'hasPermission:hub_payment_request_read',
                        ],
                        [
                            'key' => 'paid_invoice',
                            'label_trans_key' => 'invoice.paid_invoice',
                            'icon' => 'fa fa-file-invoice',
                            'route' => 'paid.invoice.index',
                            'active_patterns' => ['paid.invoice.*'],
                            'permission_check' => 'hasPermission:paid_invoice_read',
                        ],
                    ],
                ],

                [
                    'key' => 'wallet_request',
                    'label_trans_key' => 'parcel.wallet_request',
                    'icon' => 'fa fa-wallet',
                    'route' => 'wallet.request.index',
                    'active_patterns' => ['wallet.request.*'],
                    'permission_check' => 'hasPermission:wallet_request_read',
                ],
                [
                    'key' => 'online_payments',
                    'label_trans_key' => 'menus.payments_received',
                    'icon' => 'fas fa-credit-card',
                    'route' => 'online.payment.list',
                    'active_patterns' => ['online.payment.list'],
                    'permission_check' => 'hasPermission:online_payment_read',
                ],
                [
                    'key' => 'payout',
                    'label_trans_key' => 'menus.payout',
                    'icon' => 'fas fa-hand-holding-usd',
                    'route' => 'payout.index',
                    'active_patterns' => ['payout.*'],
                    'permission_check' => 'hasPermission:payout_read',
                ],
            ],
        ],

        'tools' => [
            'label_trans_key' => 'menus.tools',
            'children' => [
                [
                    'key' => 'global_search',
                    'label_trans_key' => 'menus.search',
                    'icon' => 'fa fa-search',
                    'route' => 'admin.search',
                    'active_patterns' => ['admin.search'],
                    'permission_check' => 'hasPermission:global_search_read',
                ],
                [
                    'key' => 'api_keys',
                    'label_trans_key' => 'menus.api_keys_webhooks',
                    'icon' => 'fa fa-key',
                    'route' => 'admin.api-keys.index',
                    'active_patterns' => ['admin.api-keys.*', 'admin.webhooks.*'],
                    'permission_check' => 'hasPermission:api_keys_read|hasPermission:webhooks_read',
                ],
                [
                    'key' => 'observability',
                    'label_trans_key' => 'menus.observability',
                    'icon' => 'fa fa-heartbeat',
                    'route' => 'admin.observability.index',
                    'active_patterns' => ['admin.observability.index'],
                    'permission_check' => null,
                ],
                [
                    'key' => 'exception_tower',
                    'label_trans_key' => 'menus.exception_tower',
                    'icon' => 'fa fa-exclamation-triangle',
                    'route' => 'admin.exception-tower.index',
                    'active_patterns' => ['admin.exception-tower.index'],
                    'permission_check' => null,
                ],
                [
                    'key' => 'edi',
                    'label_trans_key' => 'menus.edi_providers',
                    'icon' => 'fa fa-exchange-alt',
                    'route' => 'admin.edi.index',
                    'active_patterns' => ['admin.edi.*'],
                    'permission_check' => null,
                ],
                [
                    'key' => 'whatsapp_templates',
                    'label_trans_key' => 'menus.whatsapp_templates',
                    'icon' => 'fa fa-whatsapp',
                    'route' => 'admin.whatsapp-templates.index',
                    'active_patterns' => ['admin.whatsapp-templates.*'],
                    'permission_check' => null,
                ],
                // Site management & comms
                [
                    'key' => 'push_notification',
                    'label_trans_key' => 'menus.push_notification',
                    'icon' => 'fa fa-bell',
                    'route' => 'push-notification.index',
                    'active_patterns' => ['admin.push-notification.*', 'push-notification.*'],
                    'permission_check' => 'hasPermission:push_notification_read',
                ],
                [
                    'key' => 'addons',
                    'label_trans_key' => 'menus.addons',
                    'icon' => 'fa fa-upload',
                    'route' => 'addons.index',
                    'active_patterns' => ['admin.addons.*', 'addons.*'],
                    'permission_check' => 'env:DEMO,false',
                ],
                [
                    'key' => 'news_offer',
                    'label_trans_key' => 'menus.news_offer',
                    'icon' => 'fa fa-newspaper',
                    'route' => 'news-offer.index',
                    'active_patterns' => ['admin.news-offer.*', 'news-offer.*'],
                    'permission_check' => 'hasPermission:news_offer_read',
                ],
                [
                    'key' => 'logs',
                    'label_trans_key' => 'menus.active_logs',
                    'icon' => 'fa fa-history',
                    'route' => 'logs.index',
                    'active_patterns' => ['admin.logs.*', 'logs.*'],
                    'permission_check' => 'hasPermission:log_read',
                ],
                [
                    'key' => 'fraud',
                    'label_trans_key' => 'menus.fraud_check',
                    'icon' => 'fa fa-user-times',
                    'route' => 'fraud.index',
                    'active_patterns' => ['admin.fraud.*', 'fraud.*'],
                    'permission_check' => 'hasPermission:fraud_read',
                ],
                [
                    'key' => 'subscribe',
                    'label_trans_key' => 'account.subscribe',
                    'icon' => 'fas fa-users',
                    'route' => 'subscribe.index',
                    'active_patterns' => ['admin.subscribe.*', 'subscribe.*'],
                    'permission_check' => 'hasPermission:subscribe_read',
                ],
                [
                    'key' => 'reports',
                    'label_trans_key' => 'reports.title',
                    'icon' => 'fas fa-print',
                    'active_patterns' => ['parcel.reports', 'parcel.wise.*', 'salary.reports', 'merchant.hub.deliveryman.*', 'parcel.total.summery.*', 'reports.*'],
                    'children' => [
                        [
                            'key' => 'parcel_reports',
                            'label_trans_key' => 'reports.parcel_reports',
                            'icon' => 'fa fa-file',
                            'route' => 'parcel.reports',
                            'active_patterns' => ['parcel.reports'],
                            'permission_check' => 'hasPermission:parcel_status_reports',
                        ],
                        [
                            'key' => 'parcel_wise_profit',
                            'label_trans_key' => 'reports.parcel_wise_profit',
                            'icon' => 'fa fa-chart-line',
                            'route' => 'parcel.wise.profit.index',
                            'active_patterns' => ['parcel.wise.*'],
                            'permission_check' => 'hasPermission:parcel_wise_profit',
                        ],
                        [
                            'key' => 'salary_reports',
                            'label_trans_key' => 'reports.salary_reports',
                            'icon' => 'fa fa-file-invoice',
                            'route' => 'salary.reports',
                            'active_patterns' => ['salary.reports'],
                            'permission_check' => 'hasPermission:salary_reports',
                        ],
                        [
                            'key' => 'merchant_hub_deliveryman',
                            'label_trans_key' => 'reports.merchant_hub_deliveryman',
                            'icon' => 'fa fa-users',
                            'route' => 'merchant.hub.deliveryman.reports',
                            'active_patterns' => ['merchant.hub.deliveryman.*'],
                            'permission_check' => 'hasPermission:merchant_hub_deliveryman',
                        ],
                        [
                            'key' => 'parcel_total_summery',
                            'label_trans_key' => 'menus.parcel_total_summery',
                            'icon' => 'fa fa-sum',
                            'route' => 'parcel.total.summery.index',
                            'active_patterns' => ['parcel.total.summery.*'],
                            'permission_check' => 'hasPermission:parcel_total_summery',
                        ],
                    ],
                ],
                [
                    'key' => 'front_web',
                    'label_trans_key' => 'levels.front_web',
                    'icon' => 'fas fa-globe',
                    'active_patterns' => ['social.link.*', 'service.*', 'why.courier.*', 'faq.*', 'partner.*', 'blogs.*', 'pages.*', 'section.*'],
                    'children' => [
                        [
                            'key' => 'social_link',
                            'label_trans_key' => 'levels.social_link',
                            'icon' => 'fa fa-share-alt',
                            'route' => 'social.link.index',
                            'active_patterns' => ['social.link.*'],
                            'permission_check' => 'hasPermission:social_link_read',
                        ],
                        [
                            'key' => 'service',
                            'label_trans_key' => 'levels.service',
                            'icon' => 'fa fa-cog',
                            'route' => 'service.index',
                            'active_patterns' => ['service.*'],
                            'permission_check' => 'hasPermission:service_read',
                        ],
                        [
                            'key' => 'why_courier',
                            'label_trans_key' => 'levels.why_courier',
                            'icon' => 'fa fa-question',
                            'route' => 'why.courier.index',
                            'active_patterns' => ['why.courier.*'],
                            'permission_check' => 'hasPermission:why_courier_read',
                        ],
                        [
                            'key' => 'faq',
                            'label_trans_key' => 'levels.faq',
                            'icon' => 'fa fa-question-circle',
                            'route' => 'faq.index',
                            'active_patterns' => ['faq.*'],
                            'permission_check' => 'hasPermission:faq_read',
                        ],
                        [
                            'key' => 'partner',
                            'label_trans_key' => 'levels.partner',
                            'icon' => 'fa fa-handshake',
                            'route' => 'partner.index',
                            'active_patterns' => ['partner.*'],
                            'permission_check' => 'hasPermission:partner_read',
                        ],
                        [
                            'key' => 'blogs',
                            'label_trans_key' => 'levels.blogs',
                            'icon' => 'fa fa-blog',
                            'route' => 'blogs.index',
                            'active_patterns' => ['blogs.*'],
                            'permission_check' => 'hasPermission:blogs_read',
                        ],
                        [
                            'key' => 'pages',
                            'label_trans_key' => 'levels.pages',
                            'icon' => 'fa fa-file',
                            'route' => 'pages.index',
                            'active_patterns' => ['pages.*'],
                            'permission_check' => 'hasPermission:pages_read',
                        ],
                        [
                            'key' => 'section',
                            'label_trans_key' => 'levels.section',
                            'icon' => 'fa fa-layer-group',
                            'route' => 'section.index',
                            'active_patterns' => ['section.*'],
                            'permission_check' => 'hasPermission:section_read',
                        ],
                    ],
                ],
            ],
        ],

        'settings' => [
            'label_trans_key' => 'menus.settings',
            'children' => [
                [
                    'key' => 'user_role',
                    'label_trans_key' => 'menus.user_role',
                    'icon' => 'fas fa-th',
                    'active_patterns' => ['roles.*', 'users.*', 'designations.*', 'departments.*'],
                    'children' => [
                        [
                            'key' => 'roles',
                            'label_trans_key' => 'menus.roles',
                            'icon' => 'fa fa-user-shield',
                            'route' => 'roles.index',
                            'active_patterns' => ['roles.*'],
                            'permission_check' => 'hasPermission:role_read',
                        ],
                        [
                            'key' => 'designations',
                            'label_trans_key' => 'menus.designations',
                            'icon' => 'fa fa-id-badge',
                            'route' => 'designations.index',
                            'active_patterns' => ['designations.*'],
                            'permission_check' => 'hasPermission:designation_read',
                        ],
                        [
                            'key' => 'departments',
                            'label_trans_key' => 'menus.departments',
                            'icon' => 'fa fa-building',
                            'route' => 'departments.index',
                            'active_patterns' => ['departments.*'],
                            'permission_check' => 'hasPermission:department_read',
                        ],
                        [
                            'key' => 'users',
                            'label_trans_key' => 'menus.users',
                            'icon' => 'fa fa-user',
                            'route' => 'users.index',
                            'active_patterns' => ['users.*'],
                            'permission_check' => 'hasPermission:user_read',
                        ],
                    ],
                ],
                [
                    'key' => 'general_settings',
                    'label_trans_key' => 'menus.general_settings',
                    'icon' => 'fa fa-cogs',
                    'route' => 'general-settings.index',
                    'active_patterns' => ['general-settings.*'],
                    'permission_check' => 'hasPermission:general_settings_read',
                ],
                [
                    'key' => 'delivery_category',
                    'label_trans_key' => 'menus.delivery_category',
                    'icon' => 'fa fa-cubes',
                    'route' => 'delivery-category.index',
                    'active_patterns' => ['delivery-category.*'],
                    'permission_check' => 'hasPermission:delivery_category_read',
                ],
                [
                    'key' => 'delivery_charge',
                    'label_trans_key' => 'menus.delivery_charge',
                    'icon' => 'fa fa-money-check',
                    'route' => 'delivery-charge.index',
                    'active_patterns' => ['delivery-charge.*'],
                    'permission_check' => 'hasPermission:delivery_charge_read',
                ],
                [
                    'key' => 'delivery_type',
                    'label_trans_key' => 'menus.delivery_type',
                    'icon' => 'fa fa-shipping-fast',
                    'route' => 'delivery-type.index',
                    'active_patterns' => ['delivery-type.*'],
                    'permission_check' => 'hasPermission:delivery_type_read',
                ],
                [
                    'key' => 'liquid_fragile',
                    'label_trans_key' => 'menus.liquid_fragile',
                    'icon' => 'fa fa-flask',
                    'route' => 'liquid-fragile.index',
                    'active_patterns' => ['liquid-fragile.*'],
                    'permission_check' => 'hasPermission:liquid_fragile_read',
                ],
                [
                    'key' => 'packaging',
                    'label_trans_key' => 'menus.packaging',
                    'icon' => 'fa fa-box-open',
                    'route' => 'packaging.index',
                    'active_patterns' => ['packaging.*'],
                    'permission_check' => 'hasPermission:packaging_read',
                ],
                [
                    'key' => 'sms_settings',
                    'label_trans_key' => 'menus.sms_settings',
                    'icon' => 'fa fa-sms',
                    'route' => 'sms-settings.index',
                    'active_patterns' => ['sms-settings.*'],
                    'permission_check' => 'hasPermission:sms_settings_read',
                ],
                [
                    'key' => 'sms_send_settings',
                    'label_trans_key' => 'menus.sms_send_settings',
                    'icon' => 'fa fa-sms',
                    'route' => 'sms-send-settings.index',
                    'active_patterns' => ['sms-send-settings.*'],
                    'permission_check' => 'hasPermission:sms_send_settings_read',
                ],
                [
                    'key' => 'notification_settings',
                    'label_trans_key' => 'menus.notification_settings',
                    'icon' => 'fa fa-bell',
                    'route' => 'notification-settings.index',
                    'active_patterns' => ['notification-settings.*'],
                    'permission_check' => 'hasPermission:notification_settings_read',
                ],
                [
                    'key' => 'google_map_settings',
                    'label_trans_key' => 'menus.google_map_settings',
                    'icon' => 'fa fa-map',
                    'route' => 'googlemap-settings.index',
                    'active_patterns' => ['googlemap-settings.*'],
                    'permission_check' => 'hasPermission:notification_settings_read',
                ],
                [
                    'key' => 'mail_settings',
                    'label_trans_key' => 'menus.mail_settings',
                    'icon' => 'fa fa-envelope',
                    'route' => 'mail-settings.index',
                    'active_patterns' => ['mail-settings.*'],
                    'permission_check' => 'hasPermission:mail_settings_read',
                ],
                [
                    'key' => 'social_login_settings',
                    'label_trans_key' => 'menus.social_login_settings',
                    'icon' => 'fa fa-sign-in-alt',
                    'route' => 'social.login.settings.index',
                    'active_patterns' => ['social.login.settings.*', 'social-login-setting*'],
                    'permission_check' => 'hasPermission:social_login_settings_update',
                ],
                [
                    'key' => 'payout_setup',
                    'label_trans_key' => 'menus.payout_setup',
                    'icon' => 'fa fa-money-bill',
                    'route' => 'payout.setup.settings.index',
                    'active_patterns' => ['payout.setup.settings.*', 'settings/pay-out/setup*'],
                    'permission_check' => 'hasPermission:payout_setup_settings_read',
                ],
                [
                    'key' => 'currency',
                    'label_trans_key' => 'settings.currency',
                    'icon' => 'fa fa-coins',
                    'route' => 'currency.index',
                    'active_patterns' => ['currency.*'],
                    'permission_check' => 'hasPermission:currency_read',
                ],
                [
                    'key' => 'database_backup',
                    'label_trans_key' => 'menus.database_backup',
                    'icon' => 'fa fa-database',
                    'route' => 'database.backup.index',
                    'active_patterns' => ['database.backup.*'],
                    'permission_check' => 'hasPermission:database_backup_read',
                ],
                [
                    'key' => 'invoice_generate_menually',
                    'label_trans_key' => 'menus.invoice_generate_menually',
                    'icon' => 'fa fa-file-invoice',
                    'route' => 'invoice.generate.menually.index',
                    'active_patterns' => ['invoice.generate.menually.*'],
                    'permission_check' => 'hasPermission:invoice_generate_menually',
                ],
                [
                    'key' => 'payment_methods',
                    'label_trans_key' => 'menus.payment_method',
                    'icon' => 'fa fa-money-check',
                    'active_patterns' => ['bank.*', 'mobile-bank.*'],
                    'children' => [
                        [
                            'key' => 'banks',
                            'label_trans_key' => 'menus.banks',
                            'icon' => 'fa fa-university',
                            'route' => 'bank.index',
                            'active_patterns' => ['bank.*'],
                            'permission_check' => null,
                        ],
                        [
                            'key' => 'mobile_banks',
                            'label_trans_key' => 'menus.mobile_banks',
                            'icon' => 'fa fa-mobile-alt',
                            'route' => 'mobile-bank.index',
                            'active_patterns' => ['mobile-bank.*'],
                            'permission_check' => null,
                        ],
                    ],
                ],
            ],
        ],
    ],
];
