/**
 * Maps Font Awesome icons to Lucide React icons
 */
export const faToLucideIconMap: Record<string, string> = {
  'fa fa-home': 'Home',
  'fa fa-tachometer-alt': 'Gauge',
  'fa fa-chart-line': 'TrendingUp',
  'fa fa-file-text': 'FileText',
  'fa fa-users': 'Users',
  'fa fa-building': 'Building2',
  'fa fa-credit-card': 'CreditCard',
  'fa fa-store': 'Store',
  'fa fa-user': 'User',
  'fa fa-user-plus': 'UserPlus',
  'fa fa-dollar-sign': 'DollarSign',
  'fa fa-check-square': 'CheckSquare',
  'fa fa-message-square': 'MessageSquare',
  'fa fa-box': 'Package',
  'fa fa-clipboard-plus': 'ClipboardList',
  'fa fa-layer-group': 'Layers',
  'fa fa-route': 'Route',
  'fa fa-barcode': 'Scan',
  'fa fa-truck': 'Truck',
  'fa fa-file-signature': 'FileText',
  'fa fa-shield-alt': 'Shield',
  'fa fa-list': 'List',
  'fa fa-plane': 'Plane',
  'fa fa-shipping-fast': 'Truck',
  'fa fa-project-diagram': 'Network',
  'fa fa-gas-pump': 'Fuel',
  'fa fa-tools': 'Wrench',
  'fa fa-car-crash': 'AlertTriangle',
  'fa fa-chart-bar': 'BarChart3',
  'fa fa-calculator': 'Calculator',
  'fa fa-file-invoice-dollar': 'Receipt',
  'fa fa-hand-holding-usd': 'HandCoins',
  'fa fa-exchange-alt': 'ArrowLeftRight',
  'fa fa-cash-register': 'Receipt',
  'fa fa-file-csv': 'FileSpreadsheet',
  'fa fa-handshake': 'Handshake',
  'fa fa-address-book': 'BookUser',
  'fa fa-address-card': 'Contact',
  'fa fa-file-contract': 'ScrollText',
  'fa fa-file-invoice': 'FileText',
  'fa fa-money-bill': 'Wallet',
  'fa fa-search': 'Search',
  'fa fa-key': 'Key',
  'fa fa-heartbeat': 'Activity',
  'fa fa-exclamation-triangle': 'AlertTriangle',
  'fa fa-whatsapp': 'MessageCircle',
  'fa fa-bell': 'Bell',
  'fa fa-upload': 'Upload',
  'fa fa-newspaper': 'Newspaper',
  'fa fa-history': 'History',
  'fa fa-user-times': 'UserX',
  'fa fa-globe': 'Globe',
  'fa fa-share-alt': 'Share2',
  'fa fa-cog': 'Settings',
  'fa fa-question': 'HelpCircle',
  'fa fa-blog': 'FileText',
  'fa fa-th': 'Grid3X3',
  'fa fa-user-shield': 'Shield',
  'fa fa-id-badge': 'IdCard',
  'fa fa-cogs': 'Settings',
  'fa fa-cubes': 'Package',
  'fa fa-money-check': 'Receipt',
  'fa fa-sms': 'MessageSquare',
  'fa fa-envelope': 'Mail',
  'fa fa-map': 'Map',
  'fa fa-sign-in-alt': 'LogIn',
  'fa fa-coins': 'Coins',
  'fa fa-database': 'Database',
  'fa fa-mobile-alt': 'Smartphone',
  'fas fa-circle': 'Circle',
  'fas fa-hand-holding-usd': 'HandCoins',
  'fas fa-credit-card': 'CreditCard',
  'fas fa-print': 'Printer',
  'fas fa-users': 'Users',
  'fas fa-user-plus': 'UserPlus',
  'fas fa-address-book': 'BookUser',
  'fas fa-address-card': 'Contact',
  'fas fa-file-contract': 'ScrollText',
  'fas fa-globe': 'Globe',
  'fas fa-th': 'Grid3X3',
  'fas fa-user': 'User',
  'fas fa-university': 'Building2',
  'fas fa-money-check': 'Receipt',
  'fas fa-mobile-bank': 'Smartphone',
  'fas fa-payout': 'ArrowUpRight',
  'fas fa-money-bill': 'Wallet',
  'fas fa-file-csv': 'FileSpreadsheet',
  'fas fa-handshake': 'Handshake',
  'fas fa-file-invoice': 'FileText',
  'fas fa-search': 'Search',
  'fas fa-key': 'Key',
  'fas fa-heartbeat': 'Activity',
  'fas fa-exclamation-triangle': 'AlertTriangle',
  'fas fa-whatsapp': 'MessageCircle',
  'fas fa-exchange-alt': 'ArrowLeftRight',
  'fas fa-bell': 'Bell',
  'fas fa-upload': 'Upload',
  'fas fa-newspaper': 'Newspaper',
  'fas fa-history': 'History',
  'fas fa-user-times': 'UserX',
  'fas fa-share-alt': 'Share2',
  'fas fa-cog': 'Settings',
  'fas fa-question': 'HelpCircle',
  'fas fa-blog': 'FileText',
  'fas fa-layer-group': 'Layers',
  'fas fa-user-shield': 'Shield',
  'fas fa-id-badge': 'IdCard',
  'fas fa-cogs': 'Settings',
  'fas fa-cubes': 'Package',
  'fas fa-sms': 'MessageSquare',
  'fas fa-envelope': 'Mail',
  'fas fa-map': 'Map',
  'fas fa-sign-in-alt': 'LogIn',
  'fas fa-coins': 'Coins',
  'fas fa-database': 'Database',
  'fas fa-mobile-alt': 'Smartphone',
};

/**
 * Converts Font Awesome icon classes to Lucide React icon names
 */
export const convertFaToLucide = (faIcon: string): string => {
  if (!faIcon || typeof faIcon !== 'string') {
    return 'Circle';
  }

  // Check if it's already a Lucide icon name (no fa prefix)
  if (!faIcon.startsWith('fa ') && !faIcon.startsWith('fas ')) {
    return faIcon;
  }

  // Look up the mapping
  const lucideIcon = faToLucideIconMap[faIcon];
  return lucideIcon || 'Circle'; // Default fallback
};
